### ISSUE TITLE
Support flag aliases in SKIP

### ISSUE THREAD

**Issue by unwiredben** [Hack-a-Day/2022-Supercon6-Badge-Tools#19]
It's often hard to remember exactly what condition nc, c, nz, and z represent, so other assemblers often have aliases letting you use "eq", "neq", "lt", "gt", "gte" etc as aliases.  This also make code intention clearer.

- `skip z, n` -> `skip eq, n`
- `skip nz, n` -> `skip ne, n`
- `skip c, n` -> `skip gte, n`
- `skip nc, n` -> `skip lt, n`

**Comment by MS3FGX** [comment]
Thanks for the PR.
