### ISSUE TITLE
Add Voja's synthetic instructions

### ISSUE THREAD

**Issue by unwiredben** [Hack-a-Day/2022-Supercon6-Badge-Tools#27]
In book #1 for the badge, Voja suggested several synthetic instructions that an assembler could support:

- **RLC RX, RY** - Rotate Left RY through Carry - MOV RX, RY / ADC RX, RY
- **SL RX, RY** - Shift Left RY - MOV RX, RY / ADD RX, RY
- **LSR RY** - Logical Shift Right RY - ADD R0, 0 / RRC RY
- **CPL R0** - Complement R0 - XOR R0, 0xF
- **CPL RX, RY** - Complement RY, write to RX - MOV RX, 0xF / SUB RX, RY
- **NEG RX, RY** - Negate RY, write to RX - MOV RX, 0 / SUB RX, RY
- **NOP** - No operation - MOV R0, R0

This issue tracks work to add these to the assembler.

**Comment by unwiredben** [comment]
If skip took a label, that would be a way to solve this

**Comment by hexagon5un** [comment]
True!  Tweaking the assembler to also accept labels for JR and SKIP would do it.

**Comment by voctav** [comment]
Alternatively, JR could be changed to detect jumping past a line that assembles to more than one instruction and updating the relative label. It would break all existing programs though, maybe use a flag. It is quite error prone right now anyway and you can even jump to the middle of a goto/gosub which usually leads to really weird behavior. I do agree that named labels is the way to go though.
