### ISSUE TITLE
Web Assembler is broken for BIT and related operations

### ISSUE THREAD

**Issue by smartperson** [Hack-a-Day/2022-Supercon6-Badge-Tools#4]
Not sure where else to post this. Bug in web assembler hosted at http://cloud.wd5gnr.com/badgeasm/asm.php
I believe it affects all of the B* RG,M commands (like `BIT RG,M`). I think the `M` operand is the one that is causing problems

- `BIT R1,0` =>` 0000 1001 0100` (correct)
- `BIT R1,1` => `0000 1001 1000` (incorrect!) should be `0000 1001 0101`

**Comment by szczys** [comment]
This is interesting. I have just tested this and I see the expected outcome.

```
011  0000 1001 0101       BIT R1,1
```

Here's my Python version:

```
➜ python --version
Python 3.8.10
```

We're going to check into the web compiler and see if there's some version issue that's causing this.

**Comment by MS3FGX** [comment]
@szczys That does indeed seem to be the problem, the version of the assembler pulled from Git when the web version was set up a few weeks back must predate when Elliot identified and fixed this particular issue.

**Comment by wd5gnr** [comment]
Very strange. For some reason this worked from command line on server, but not from web without the addition of some (). Please test now and I think it is working.

**Comment by smartperson** [comment]
@wd5gnr you fixed it on the website, as we discussed in Discord. Thanks. Closing this issue now.
